baseURL = "https://okanbulut.netlify.com/"
title = "Okan Bulut"
copyright = "Copyright&copy; 2020 Okan Bulut. All rights reserved."
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Okan Bulut"
  description = "A blog on data science using R"
  homepageImage = "/images/homepage-image.jpg"
  share = true
  showLanguageSwitcher = false
  

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = true
    email = "bulut@ualberta.ca"
    twitter = "https://twitter.com/drokanbulut"
    linkedin = "www.linkedin.com/in/drokanbulut"
    github = "https://github.com/okanbulut"
    medium = "https://medium.com"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
